tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "ccat"
brew "chisel"
brew "duti"
brew "hub"
brew "jq"
brew "mas"
brew "midnight-commander"
brew "rbenv"
brew "swiftgen"
brew "tig"
brew "zsh-autosuggestions"
cask "alfred"
cask "appcleaner"
cask "daisydisk"
cask "spotify"
cask "google-chrome"
cask "iterm2"
cask "paw"
cask "proxyman"
cask "sublime-text"
cask "transmission"
cask "windscribe"
cask "ksdiff"
mas "AdGuard for Safari", id: 1440147259
mas "Dark Mode for Safari", id: 1397180934
mas "DevCleaner", id: 1388020431
mas "Magnet", id: 441258766
mas "Telegram", id: 747648890
