#!/bin/sh

url() {
	curl -X GET --compressed $@ | jq
}

ru() {
	lang=$LANG
	export LANG=ru_RU.UTF-8
	eval "$1"
	export LANG=$lang
}

quarantine() {
	sudo xattr -rd com.apple.quarantine /Applications/"$1".app
}

upgrade_dotfiles() {
	dotfiles && gpl && cd -
}

upgrade_all() {
	upgrade_oh_my_zsh; 
	brew upgrade; 
	echo 'Updating powerlevel10k'
	git -C $ZSH_CUSTOM/themes/powerlevel10k pull
	echo 'Updating dotfiles'
	upgrade_dotfiles;
}