#!/bin/sh

# homebrew
brew doctor
(cd ~/.dotfiles; brew bundle)

# duti
echo "com.sublimetext.3   public.plain-text all" | duti
echo "com.sublimetext.3   public.unix-executable all" | duti
duti -s com.sublimetext.3 .mod all
duti -s com.sublimetext.3 .dat all
duti -s com.sublimetext.3 .run all
duti -s com.sublimetext.3 .tex all
duti -s com.sublimetext.3 .json all
duti -s com.sublimetext.3 .php all
duti -s com.sublimetext.3 .md all
duti -s com.sublimetext.3 .txt all
duti -s com.sublimetext.3 .py all

# oh-my-zsh
exec zsh
rm ~/.zshrc

# rbenv
rbenv init
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
gem install bundler
gem install xcode-install 
gem install cocoapods 
gem install fastlane 

# symlink dotfiles
ln -s ~/.dotfiles/.tigrc ~/.tigrc
ln -s ~/.dotfiles/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/.gitignore ~/.gitignore
ln -s ~/.dotfiles/.zshrc ~/.zshrc