#!/bin/sh

# oh-my-zsh
open -a iTerm
sleep 2
rm ~/.zshrc

# symlink dotfiles
ln -s ~/.dotfiles/.tigrc ~/.tigrc
ln -s ~/.dotfiles/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/.gitignore ~/.gitignore
ln -s ~/.dotfiles/.zshrc ~/.zshrc

# homebrew
brew doctor
(cd ~/.dotfiles; brew bundle)

# duti
echo "com.sublimetext.3   public.plain-text all" | duti
echo "com.sublimetext.3   public.unix-executable all" | duti
duti -s com.sublimetext.3 .mod all
duti -s com.sublimetext.3 .dat all
duti -s com.sublimetext.3 .run all
duti -s com.sublimetext.3 .tex all
duti -s com.sublimetext.3 .json all
duti -s com.sublimetext.3 .php all
duti -s com.sublimetext.3 .md all
duti -s com.sublimetext.3 .txt all
duti -s com.sublimetext.3 .py all

# rbenv
rbenv init
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
rbenv install --list
read -p "Ruby version: " version
rbenv install $version
rbenv global $version
read -p "Gems to install: " gems
gem install $gems

#configure git
echo 'Git:'
read -p "Name: " name
git config --global user.name $name
read -p "Email: " email
git config --global user.email $email
read -p "Github user: " user
git config --global github.user $user